export let LOG_IN = 'LOG_IN'
export let LOG_OUT = 'LOG_OUT'

export let CHANGE_VIEW = 'CHANGE_VIEW'

export let FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST'
export let FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'
export let FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE'
